variables:
  DOCKER_REGISTRY: 613539523857.dkr.ecr.ap-southeast-1.amazonaws.com
  AWS_DEFAULT_REGION: ap-southeast-1
  APP_NAME: gis_ckc-user-mnt
  #APP_VERSION: 1.0.1
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

build:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - cat /etc/os-release  
    - docker --version
  script:
    #- docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID -f "deploy/Dockerfile" . 
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:develop -f "deploy/Dockerfile" . 
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    #- docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
    - docker push $DOCKER_REGISTRY/$APP_NAME:develop
  only:
    - tags
    
deploy:
  only:
    - tags
  stage: deploy
  script:
    - echo "Deploy steps go here..."
